// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Stream struct {
	ID                 int32              `db:"id" json:"id"`
	Name               string             `db:"name" json:"name"`
	Key                string             `db:"key" json:"key"`
	HasCustomThumbnail pgtype.Bool        `db:"has_custom_thumbnail" json:"has_custom_thumbnail"`
	IsVod              pgtype.Bool        `db:"is_vod" json:"is_vod"`
	IsActive           pgtype.Bool        `db:"is_active" json:"is_active"`
	TotalViews         pgtype.Int4        `db:"total_views" json:"total_views"`
	StartedAt          pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt            pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	UserID             int32              `db:"user_id" json:"user_id"`
}

type User struct {
	ID            int32       `db:"id" json:"id"`
	Name          string      `db:"name" json:"name"`
	Email         string      `db:"email" json:"email"`
	PasswordHash  string      `db:"password_hash" json:"password_hash"`
	RememberToken pgtype.Text `db:"remember_token" json:"remember_token"`
}

type View struct {
	ID         int32       `db:"id" json:"id"`
	IsWatching pgtype.Bool `db:"is_watching" json:"is_watching"`
	GuestToken pgtype.Text `db:"guest_token" json:"guest_token"`
	UserID     pgtype.Int4 `db:"user_id" json:"user_id"`
	StreamID   int32       `db:"stream_id" json:"stream_id"`
}
