// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: views.sql

package sqlc

import (
	"context"
)

const removeStreamViewers = `-- name: RemoveStreamViewers :exec
DELETE FROM views
WHERE stream_id = $1
`

// RemoveStreamViewers
//
//	DELETE FROM views
//	WHERE stream_id = $1
func (q *Queries) RemoveStreamViewers(ctx context.Context, streamID int32) error {
	_, err := q.db.Exec(ctx, removeStreamViewers, streamID)
	return err
}

const unviewStreamAsGuest = `-- name: UnviewStreamAsGuest :exec
SELECT unview_stream_as_guest($1, $2)
AS stream_found
`

type UnviewStreamAsGuestParams struct {
	GuestToken string `db:"guest_token" json:"guest_token"`
	StreamKey  string `db:"stream_key" json:"stream_key"`
}

// UnviewStreamAsGuest
//
//	SELECT unview_stream_as_guest($1, $2)
//	AS stream_found
func (q *Queries) UnviewStreamAsGuest(ctx context.Context, arg UnviewStreamAsGuestParams) error {
	_, err := q.db.Exec(ctx, unviewStreamAsGuest, arg.GuestToken, arg.StreamKey)
	return err
}

const unviewStreamAsUser = `-- name: UnviewStreamAsUser :exec
SELECT unview_stream_as_user($1, $2)
AS stream_found
`

type UnviewStreamAsUserParams struct {
	UserID    int32  `db:"user_id" json:"user_id"`
	StreamKey string `db:"stream_key" json:"stream_key"`
}

// UnviewStreamAsUser
//
//	SELECT unview_stream_as_user($1, $2)
//	AS stream_found
func (q *Queries) UnviewStreamAsUser(ctx context.Context, arg UnviewStreamAsUserParams) error {
	_, err := q.db.Exec(ctx, unviewStreamAsUser, arg.UserID, arg.StreamKey)
	return err
}

const viewStreamAsGuest = `-- name: ViewStreamAsGuest :one
SELECT view_stream_as_guest($1, $2)
AS stream_found
`

type ViewStreamAsGuestParams struct {
	GuestToken string `db:"guest_token" json:"guest_token"`
	StreamKey  string `db:"stream_key" json:"stream_key"`
}

// ViewStreamAsGuest
//
//	SELECT view_stream_as_guest($1, $2)
//	AS stream_found
func (q *Queries) ViewStreamAsGuest(ctx context.Context, arg ViewStreamAsGuestParams) (bool, error) {
	row := q.db.QueryRow(ctx, viewStreamAsGuest, arg.GuestToken, arg.StreamKey)
	var stream_found bool
	err := row.Scan(&stream_found)
	return stream_found, err
}

const viewStreamAsUser = `-- name: ViewStreamAsUser :one
SELECT view_stream_as_user($1, $2) 
AS stream_found
`

type ViewStreamAsUserParams struct {
	UserID    int32  `db:"user_id" json:"user_id"`
	StreamKey string `db:"stream_key" json:"stream_key"`
}

// ViewStreamAsUser
//
//	SELECT view_stream_as_user($1, $2)
//	AS stream_found
func (q *Queries) ViewStreamAsUser(ctx context.Context, arg ViewStreamAsUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, viewStreamAsUser, arg.UserID, arg.StreamKey)
	var stream_found bool
	err := row.Scan(&stream_found)
	return stream_found, err
}
