// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUser = `-- name: AddUser :one
INSERT INTO users (name, email, password_hash) 
VALUES 
(
  $1, 
  $2,
  $3
) 
ON CONFLICT (email) DO NOTHING 
RETURNING id
`

type AddUserParams struct {
	Name         string `db:"name" json:"name"`
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

// AddUser
//
//	INSERT INTO users (name, email, password_hash)
//	VALUES
//	(
//	  $1,
//	  $2,
//	  $3
//	)
//	ON CONFLICT (email) DO NOTHING
//	RETURNING id
func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, addUser, arg.Name, arg.Email, arg.PasswordHash)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const checkUserById = `-- name: CheckUserById :one
SELECT 1
FROM users
WHERE id = $1 
LIMIT 1
`

// CheckUserById
//
//	SELECT 1
//	FROM users
//	WHERE id = $1
//	LIMIT 1
func (q *Queries) CheckUserById(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, checkUserById, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserCredentialsByEmail = `-- name: GetUserCredentialsByEmail :one
SELECT id, password_hash
FROM users
WHERE email = $1 
LIMIT 1
`

type GetUserCredentialsByEmailRow struct {
	ID           int32  `db:"id" json:"id"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

// GetUserCredentialsByEmail
//
//	SELECT id, password_hash
//	FROM users
//	WHERE email = $1
//	LIMIT 1
func (q *Queries) GetUserCredentialsByEmail(ctx context.Context, email string) (GetUserCredentialsByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialsByEmail, email)
	var i GetUserCredentialsByEmailRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const getUserDataById = `-- name: GetUserDataById :one
SELECT name, email
FROM users
WHERE id = $1 
LIMIT 1
`

type GetUserDataByIdRow struct {
	Name  string `db:"name" json:"name"`
	Email string `db:"email" json:"email"`
}

// GetUserDataById
//
//	SELECT name, email
//	FROM users
//	WHERE id = $1
//	LIMIT 1
func (q *Queries) GetUserDataById(ctx context.Context, userID int32) (GetUserDataByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserDataById, userID)
	var i GetUserDataByIdRow
	err := row.Scan(&i.Name, &i.Email)
	return i, err
}

const getUserDataByRememberToken = `-- name: GetUserDataByRememberToken :one
SELECT id, name, email 
FROM users 
WHERE remember_token = $1
LIMIT 1
`

type GetUserDataByRememberTokenRow struct {
	ID    int32  `db:"id" json:"id"`
	Name  string `db:"name" json:"name"`
	Email string `db:"email" json:"email"`
}

// GetUserDataByRememberToken
//
//	SELECT id, name, email
//	FROM users
//	WHERE remember_token = $1
//	LIMIT 1
func (q *Queries) GetUserDataByRememberToken(ctx context.Context, rememberToken pgtype.Text) (GetUserDataByRememberTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserDataByRememberToken, rememberToken)
	var i GetUserDataByRememberTokenRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const getUserIdByRememberToken = `-- name: GetUserIdByRememberToken :one
SELECT 1 
FROM users 
WHERE remember_token = $1
LIMIT 1
`

// GetUserIdByRememberToken
//
//	SELECT 1
//	FROM users
//	WHERE remember_token = $1
//	LIMIT 1
func (q *Queries) GetUserIdByRememberToken(ctx context.Context, rememberToken pgtype.Text) (int32, error) {
	row := q.db.QueryRow(ctx, getUserIdByRememberToken, rememberToken)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const resetRememberToken = `-- name: ResetRememberToken :exec
UPDATE users 
SET remember_token = NULL 
WHERE remember_token = $1
`

// ResetRememberToken
//
//	UPDATE users
//	SET remember_token = NULL
//	WHERE remember_token = $1
func (q *Queries) ResetRememberToken(ctx context.Context, rememberToken pgtype.Text) error {
	_, err := q.db.Exec(ctx, resetRememberToken, rememberToken)
	return err
}

const resetUserRememberToken = `-- name: ResetUserRememberToken :exec
UPDATE users 
SET remember_token = NULL 
WHERE id = $1
`

// ResetUserRememberToken
//
//	UPDATE users
//	SET remember_token = NULL
//	WHERE id = $1
func (q *Queries) ResetUserRememberToken(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, resetUserRememberToken, userID)
	return err
}

const updateUserRememberToken = `-- name: UpdateUserRememberToken :exec
UPDATE users 
SET remember_token = $1 
WHERE id = $2
`

type UpdateUserRememberTokenParams struct {
	RememberToken pgtype.Text `db:"remember_token" json:"remember_token"`
	UserID        int32       `db:"user_id" json:"user_id"`
}

// UpdateUserRememberToken
//
//	UPDATE users
//	SET remember_token = $1
//	WHERE id = $2
func (q *Queries) UpdateUserRememberToken(ctx context.Context, arg UpdateUserRememberTokenParams) error {
	_, err := q.db.Exec(ctx, updateUserRememberToken, arg.RememberToken, arg.UserID)
	return err
}
